# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Load from CSV
csv_input = "../output_data/City_Data.csv"
initialDF = pd.read_csv(csv_input)
initialDF

,Unnamed: 0,Name,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Tasiilaq,65.61,-37.64,276.15,93,97,4.10,GL,1595550546
1,1,ÅŒmachi,36.50,137.87,295.93,83,75,5.70,JP,1595550547
2,2,Kapaa,22.08,-159.32,303.15,70,40,5.10,US,1595550326
3,3,Souillac,-20.52,57.52,293.15,60,40,6.70,MU,1595550443
4,4,Busselton,-33.65,115.33,279.26,80,3,2.84,AU,1595550547
5,5,Upernavik,72.79,-56.15,280.89,77,69,4.81,GL,1595550444
6,6,Thompson,55.74,-97.86,302.15,54,40,4.60,CA,1595550548
7,7,Atuona,-9.80,-139.03,299.56,75,4,7.68,PF,1595550549
8,8,Shawnee,39.05,-95.77,305.15,59,1,2.10,US,1595550549
9,9,Arlit,18.74,7.39,307.18,35,43,5.50,NE,1595550549
10,10,Mataura,-46.19,168.86,277.04,83,83,1.34,NZ,1595550184
11,11,Ilulissat,69.22,-51.10,285.15,66,100,1.50,GL,1595550549
12,12,Ushuaia,-54.80,-68.30,277.15,85,40,5.10,AR,1595550145
13,13,Lundazi,-12.29,33.18,285.27,76,0,4.04,ZM,1595550550
14,14,Deputatsky,69.30,139.90,299.08,34,65,1.28,RU,1595550550
15,15,Calabozo,8.92,-67.43,297.98,87,23,1.75,VE,1595550551
16,16,Tiarei,-17.53,-149.33,297.15,83,75,4.10,PF,1595550551
17,17,Laramie,41.31,-105.59,299.15,22,1,2.60,US,1595550552
18,18,Ust-Tsilma,65.44,52.15,289.68,79,81,2.44,RU,1595550552
19,19,Hermanus,-34.42,19.23,285.93,81,0,0.45,ZA,1595550552
20,20,Nome,64.50,-165.41,282.15,87,90,4.60,US,1595550553
21,21,GÅ‚ogÃ³w,51.66,16.08,288.15,82,8,1.78,PL,1595550553
22,22,Nikolayevsk-on-Amur,53.14,140.73,290.99,51,41,1.68,RU,1595550553
23,23,Vestmannaeyjar,63.44,-20.27,283.15,93,90,4.10,IS,1595550553
24,24,Sorong,-0.88,131.25,299.72,84,37,3.12,ID,1595550554
25,25,Doha,25.29,51.53,307.15,66,0,2.10,QA,1595550554
26,26,Jamestown,42.10,-79.24,297.59,83,90,3.10,US,1595550554
27,27,Cherskiy,68.75,161.30,294.49,57,9,4.67,RU,1595550523

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [39]:
# Create Humidity DataFrame
humidityDF = initialDF[['Latitude','Longitude','Humidity']]
humidityData = humidityDF.to_dict()

# Configure gmaps
gmaps.configure(api_key=g_key)
m = gmaps.Map()
try:
    heatmap_layer = gmaps.heatmap_layer(humidityDF[['Latitude','Longitude']],
                                        weights=humidityDF['Humidity'],
                                        max_intensity=150,
                                        point_radius=10.0)
    m.add_layer(heatmap_layer)
except:
    print("You come to the depressing realization that this code does not work.")
m

Map(configuration={'api_key': 'AIzaSyDB4J-6sML4PfxkUNgq211HZGYz-YtjDww'}, data_bounds=[(-53.83132382164568, -1â€¦

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure